### ISSUE TITLE
Design Mobile Site

### ISSUE THREAD

**Issue by RedbackThomson** [SDHacks/SDHacks2017#3]
We need to make our beautiful desktop design into a fully fleshed out mobile design. This includes a fully-functional user registration form.

**Comment by RedbackThomson** [comment]
Actually, the user registration form will be placed on an entirely different page. So we probably shouldn't include it in the front-page design. That spec can be moved to the registration page issue. #8

**Comment by liawesomesaucer** [comment]
Finished
