### ISSUE TITLE
Design User Profile Pages

### ISSUE THREAD

**Issue by RedbackThomson** [SDHacks/SDHacks2017#6]
Since we will be converting user pages into the React back-end, we need an all new design that easily allows for users to see and update their profiles, but gives flexibility to admins to make any modifications they want. Therefore, this design will need to accommodate every field that we store for the admin, and then hide the private fields when not being accessed by an admin.

**Comment by huy-qn** [comment]
Is this still considered as an issue?

**Comment by liawesomesaucer** [comment]
@gangstafat you're right, haven't updated recently, closing this
